/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Custom T-Shirt Studio API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  category: string;
  sizes: string[];
  colors: string[];
  featured: boolean;
  stock: number;
}

export interface CartItem {
  itemId: string;
  productId: number;
  productName: string;
  productImageUrl: string;
  size: string;
  color: string;
  quantity: number;
  price: number;
  customDesignUrl?: string | null;
}

export interface Cart {
  items: CartItem[];
  total: number;
  itemCount: number;
}

export interface AddCartItemBody {
  productId: number;
  size: string;
  color: string;
  quantity: number;
  customDesignUrl?: string | null;
}

export interface CreateOrderBody {
  customerName: string;
  email: string;
  address: string;
  city: string;
  country: string;
  zipCode: string;
  items: AddCartItemBody[];
}

export interface Order {
  id: number;
  customerName: string;
  email: string;
  address: string;
  city: string;
  country: string;
  zipCode: string;
  status: string;
  total: number;
  items: CartItem[];
  createdAt: string;
}

export interface UploadDesignBody {
  /** Base64 encoded image data (with data URI prefix) */
  imageData: string;
  filename: string;
}

export interface UploadResult {
  url: string;
  filename: string;
}

export type ListProductsParams = {
  category?: string;
};
