export { productsTable } from "./schemas/products.js";
export type { Product, InsertProduct } from "./schemas/products.js";
export { ordersTable } from "./schemas/orders.js";
export type { Order, InsertOrder } from "./schemas/orders.js";
export { leadsTable } from "./schemas/leads.js";
export type { Lead } from "./schemas/leads.js";
export { settingsTable } from "./schemas/settings.js";
export type { Setting } from "./schemas/settings.js";
export { uploadsTable } from "./schemas/uploads.js";
export type { Upload } from "./schemas/uploads.js";
